<script type="text/javascript" src="<spring:url value="/js/ajax-solr-06-01-2013/core/Core.js" />"></script>
<script type="text/javascript" src="<spring:url value="/js/ajax-solr-06-01-2013/core/AbstractManager.js" />"></script>
<script type="text/javascript" src="<spring:url value="/js/ajax-solr-06-01-2013/core/AbstractWidget.js" />"></script>
<script type="text/javascript" src="<spring:url value="/js/ajax-solr-06-01-2013/managers/Manager.jquery.js" />"></script>
<script type="text/javascript" src="<spring:url value="/js/ajax-solr-06-01-2013/core/Parameter.js" />"></script>
<script type="text/javascript" src="<spring:url value="/js/ajax-solr-06-01-2013/core/ParameterStore.js" />"></script>
<script type="text/javascript" src="<spring:url value="/js/jquery/ajaxsolr.custom/lib/helpers/jquery/ajaxsolr.theme.js" />"></script>
<script type="text/javascript" src="<spring:url value="/js/jquery/ajaxsolr.custom/lib/helpers/ajaxsolr.support.js" />"></script>
<script type="text/javascript" src="<spring:url value="/js/jquery/ajaxsolr.custom/lib/helpers/ajaxsolr.theme.js" />"></script>